name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  cuda-11:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build and push runtime image 11.4
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: doku9652/minicuda:11.4.3-runtime
          build-args: |
            NV_CUDA_BASE=11.4
            NV_CUDA_SUB=3
            NV_CUDNN=8
            NV_OS=ubuntu20.04
            NV_FLAVOR=runtime
      -
        name: Build and push runtime image 11.6
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: doku9652/minicuda:11.6.2-runtime
          build-args: |
            NV_CUDA_BASE=11.6
            NV_CUDA_SUB=2
            NV_CUDNN=8
            NV_OS=ubuntu20.04
            NV_FLAVOR=runtime
      -
        name: Build and push devel image 11.4
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: doku9652/minicuda:11.4.3-devel
          build-args: |
            NV_CUDA_BASE=11.4
            NV_CUDA_SUB=3
            NV_CUDNN=8
            NV_OS=ubuntu20.04
            NV_FLAVOR=devel
      -
        name: Build and push devel image 11.6
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: doku9652/minicuda:11.6.2-devel
          build-args: |
            NV_CUDA_BASE=11.6
            NV_CUDA_SUB=2
            NV_CUDNN=8
            NV_OS=ubuntu20.04
            NV_FLAVOR=devel
